config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'lol' => 'pages#lol'

  resources :categories


  post '/goals/:goal_id/buddyup' => 'goals#buddyup'

  post '/goals/:goal_id/achieved' => 'goals#achieved'
  # post 'goals/:goal_id/buddyup' => 'goals#buddyup'

  resources :goals do
    resources :orders do
    end

    resources :messages do
    end

    resources :subgoals do
    end
  end

  get '/users/edit' => 'users#edit'

  resources :users, :only => [:new, :create, :index, :update, :show]

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'



end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  amount        :integer
#  user_paid     :boolean          default(FALSE)
#  user_refunded :boolean          default(FALSE)
#  vault_paid    :boolean          default(FALSE)
#  goal_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Order < ActiveRecord::Base
  belongs_to :goal
end

app/controllers/orders_controller.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  amount        :integer
#  user_paid     :boolean          default(FALSE)
#  user_refunded :boolean          default(FALSE)
#  vault_paid    :boolean          default(FALSE)
#  goal_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class OrdersController < ApplicationController

  def new
    @goal = Goal.find params[:goal_id]
    @amount = @goal.amount * 100
end

  def create
    # Amount in cents
    @goal = Goal.find params[:goal_id]
    @amount = @goal.amount * 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
    order = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'BuddyUp customer',
      :currency    => 'aud'
    )
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_goal_order_path
  end
end

app/helpers/orders_helper.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  amount        :integer
#  user_paid     :boolean          default(FALSE)
#  user_refunded :boolean          default(FALSE)
#  vault_paid    :boolean          default(FALSE)
#  goal_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

module OrdersHelper
end

app/views/orders/create.html.erb
  <div class="main__title">
  <h2>Thanks, you have pledged <strong>$<%= sprintf("%.2f", @amount / 100.0) %></strong>!</h2>
  </div>
  <div class="text-center">
<p>Congratulations, you are on your way to achieving your goal.</p>
<p>Why not set up some targets to start you on your journey?</p>
</div>
<div class="btn-container">
  <%= link_to 'See Your Goal', goal_path(@goal), :class => 'btn' %>
</div>
<div class="quote-each__quote">
<p>"Start by doing what's necessary; then do what's possible; and suddenly you are doing the
impossible"</p>
</div>
</div>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<div class="container">
<div class="main">
<h1 class='main__title'>Charity of the Month</h1>
<h2 class='main__title'>Badger Trust</h2>
<div class="user-each__container">
<div class ="user-each__user-pic">
<%= image_tag('badger.gif', :crop => :fill, :class => "user-each__user-pic") %>
</div>
</div>
<p>Badgers are very close to our hearts here at Buddy Up and we are pleased to announce
  that the Badger Trust is our Charity of the month. Once your goal is achieved your
  $<%= sprintf("%.2f", @amount / 100.0) %> pledge will go towards caring for this wonderful creature.
  Thank you from the BuddyUp team and the Badger Trust</p>
</div>

<div class="user-each__container">
<div class="text-align">

<%= form_tag goal_orders_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount $<%= sprintf("%.2f", @amount / 100.0)%></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Goal pledge"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>
</div>
</div>
</div>
</div>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>