config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'lol' => 'pages#lol'

  resources :categories


  post '/goals/:goal_id/buddyup' => 'goals#buddyup'

  post '/goals/:goal_id/achieved' => 'goals#achieved'
  # post 'goals/:goal_id/buddyup' => 'goals#buddyup'

  resources :goals do
    resources :orders do
    end

    resources :messages do
    end

    resources :subgoals do
    end
  end

  get '/users/edit' => 'users#edit'

  resources :users, :only => [:new, :create, :index, :update, :show]

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'



end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  achieved     :boolean          default(FALSE)
#  acceptor_id  :integer
#  initiator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  amount       :integer
#

class Goal < ActiveRecord::Base
  belongs_to :acceptor, class_name: "User", foreign_key: "acceptor_id"
  belongs_to :initiator, class_name: "User", foreign_key: "initiator_id"
  has_and_belongs_to_many :categories
  has_many :subgoals, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :messages, dependent: :destroy
    attr_accessor :created_date_formatted, :created_date_ago, :this_is_the_date
    def attributes
      #super.merge('this_is_the_date' => self.this_is_the_date )
      super.merge('created_date_ago' => self.created_date_ago)
    end
end

app/controllers/goals_controller.rb
# == Schema Information
#
# Table name: goals
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  achieved     :boolean          default(FALSE)
#  acceptor_id  :integer
#  initiator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  amount       :integer
#

class GoalsController < ApplicationController

require "action_view"
include ActionView::Helpers::DateHelper

  def edit
    @goal = Goal.find params[:id]
    @categories = Category.all
  end

  def update
    goal = Goal.find params[:id]
    goal.update goal_params
    redirect_to goal_path
  end

  def index
    @categories = Category.all

    if @current_user.present?
      @goals = Goal.where(:acceptor_id => nil) - Goal.where(:initiator_id => @current_user.id) - Goal.where(:initiator_id => nil)
    else
      @goals = Goal.all
    end
    @goals.map! do |goal|
      #goal.this_is_the_date = goal.created_at
      goal.created_date_ago = distance_of_time_in_words_to_now(goal.created_at)
      #goal.killme = time_tag(goal.created_date)
      goal
    end

    respond_to do |format|
      format.html { }
      format.json { render json: @goals.to_json(:include => [:categories, :initiator]) }
    end
    puts(@goals.inspect)
  end



  def new
    @goal = Goal.new
    @categories = Category.all
  end

  def create
    @goal = Goal.new goal_params
    @goal.initiator = @current_user
    @error_amount = @goal[:amount]

    if @goal.save
      redirect_to new_goal_order_path(@goal)
    else
      render 'new'
    end
  end

  def show
    @goal = Goal.find params[:id]
    @subgoal = Subgoal.new
    @messages = @goal.messages
    @subgoals = @goal.subgoals

    respond_to do |format|
      format.html
      format.json{
        render :json => @goal.to_json
      }
    end

  end

  def destroy
    goal = Goal.find params[:id]

    @user = User.all

    goal.destroy
    redirect_to user_path(@current_user)

  end

  def achieved
    @goal = Goal.find params[:id]
    @goal.achieved = true
    @goal.save
    redirect_to user_path(@current_user)
  end

  def buddyup
    @goal = Goal.find params[:goal_id]
    @goal.acceptor = @current_user # not <<

    @goal.save
    redirect_to new_goal_order_path params[:goal_id]

  end

  private
  def goal_params
    params.require(:goal).permit(:title, :description, :achieved, :acceptor_id, :initiator_id, :amount, category_ids: [])
    # ^^ category_ids: [] is equiv to :category_ids => []
  end
end

app/helpers/goals_helper.rb
# == Schema Information
#
# Table name: goals
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  achieved     :boolean          default(FALSE)
#  acceptor_id  :integer
#  initiator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  amount       :integer
#

module GoalsHelper

  def goal_status(goal)
    if goal.achieved
      status = "Congratulations, you've achieved your goal"
    else
      status = "In progress"
    end
  end

end

app/views/goals/_categories_list.html.erb
<% @categories.each do |c| %>
  <p>
    <div class='category_btn' class="btn btn__buddy-up--before">
    <%= link_to c.title, c, "cat_id" => c.id %>
    </div>
    <% if @current_user.admin? && c.goals.length == 0 %>
      <%= link_to 'Delete', category_path(c), :method => :delete , :class => 'link' %>
    <% end %>
  </p>
<% end %>

<div class="btn-container">
  <% if @current_user.admin? %>
    <%= link_to 'Add Category', new_category_path, :class => 'btn' %>
  <% end %>
</div>

app/views/goals/_form.html.erb
<%= form_for @goal, :html => { :class => 'goal-form' } do |f| %>

<div class="modal__container">
  <div class="modal">
    <h2 class="modal__title">Oh no!</h2>
    <div class="modal__text">
      <p>Please be sure to pledge a minimum of $50</p>
    </div>
    <div class="modal__buttons">
      <%= link_to "Try Again", new_goal_path, :class => 'btn btn__buddy-up--cancel' %>
    </div>
  </div>
</div>


  <fieldset>
    <%= f.label :title, :class => 'label' %>
    <%= f.text_field :title, :class => 'input' %>
  </fieldset>

  <fieldset>
    <%= f.label :description, :class => 'label' %>
    <%= f.text_field :description, :class => 'input' %>
  </fieldset>

  <fieldset id="category__checkbox">
    <%= f.label :category_id, :class => 'label' %>
    <%= f.collection_check_boxes :category_ids, @categories, :id, :title do |c| %>
      <%= c.check_box( :class => 'checkbox' ) %>
      <%= c.label %>
    <% end %>
    <div id="errorMessage"></div>
  </fieldset>

  <fieldset id="category__amount">
    <%= f.label :amount, :class => 'label' %>
    <%= f.number_field :amount, :class => 'input', :placeholder => 'Please pledge a minimum of $50' %>
  </fieldset>

  <div class="btn-container">
    <%= f.submit :class => 'btn', :id => "amount" %>
  </div>

<% end %>

app/views/goals/_subgoals_list.html.erb
<% subgoals.each do |subgoal| %>
<div class="subgoal-each__container">
  <%= form_for ([goal, subgoal]), { remote: true } do |f| %>
  <div class="subgoal-checkbox__container">
    <input class="checkbox subgoal-checkbox__display" type="checkbox" <%= subgoal.completed ? "checked" : "" %> disabled>

    <% magic = subgoal.completed ? "1" : "0" %>
    <%= f.check_box :completed, { :class => 'checkbox subgoal-checkbox__input' } %>

  </div>

  <div class="subgoal-title__container">
    <div class="subgoal-title__text"><%= subgoal.title %></div>
    <!-- <input class="input subgoal-title__input" type="text" value="<%= subgoal.title %>"> -->
    <%= f.text_field :title, :class => 'input subgoal-title__input' %>
  </div>

  <div class="subgoal-edit__container">
    <a class="subgoal-edit__link" href="">Edit</a>

    <%= f.submit "Save", :class => 'subgoal-save__link' %>
  </div>
  <div class="subgoal-delete__container">
    <%= link_to "Delete", goal_subgoal_path(subgoal.goal_id, subgoal.id), :method => 'delete', :remote => true, :class => "what" %>
  </div>
  <% end %>

</div>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render :partial => 'form' %>

app/views/goals/index.html.erb
<script type="text/javascript">
  $(document).ready(function () {
    _.templateSettings = {
      interpolate: /\{\{\=(.+?)\}\}/g,
      evaluate: /\{\{(.+?)\}\}/g
    };
    var template = _.template($("#goals_list").html());
    var goalList;
    var filterGoals;
    $.ajax({
      url: "/goals",
      dataType: "json",
      cache: false,
      success: function (data) {
        goalList = data;
        _.each(data, function (goal) {
          $('#all_goals').append(template(goal))
        });
        $('.goal-each__more-info').on('click', function (e) {
          console.log($(this).parent().parent());
          e.preventDefault();
          $(this).parent().parent().find('.goal-each__initiator-country').toggle();
          $(this).parent().parent().find('.goal-each__goal-description').toggle();
        });
        $('.btn__buddy-up--before').on('click', function (e) {
          e.preventDefault();
          console.log('clicked');
          $('.modal__container').show();
          $('.modal-goal').text($(this).attr('goal'));
          $('.modal-initiator').text($(this).attr('initiator'));
          $('.btn__buddy-up--confirm').attr({
            href: "/goals/" + $(this).attr('goal_id') + "/buddyup"
          });
        });

        $('.category_btn').on('click', function (e) {
            e.preventDefault();
            // console.log(goalList[goalList.length-1]); var cat = [{id: +e.target.getAttribute("cat_id") }]
            var cat = +e.target.getAttribute("cat_id");
            // console.log(cat);
            filterGoals = _.filter(goalList, function (goal) {
                          console.log(goal.acceptor_id);
              for (var i = 0; i < goal.categories.length; i++) {
                if ((cat === goal.categories[i].id)){
                  return true;
                }
              }
            }); //closes filter

          $("#all_goals").html("");
          console.log(filterGoals);
          _.each(filterGoals, function (goal) {
            console.log($('#all_goals').html());
            $('#all_goals').append(template(goal));
          });//closes each
          // console.log(goal.categories, cat, _.intersection(goal.categories, cat )); return _.intersection(goal.categories, cat ).length > 0; e.target.getAttribute("cat_id"));
        }); //closes button function
      } //close success
  });
});
</script>
<script type="text/template" id="goals_list">
  <div class="goal-each__container">
    <div class="goal-each__title">

      <!-- <p> link_to goal.title.titleize, goal_path(goal)</p> -->
      <p>{{= title }}</p>
    </div>
    <div class="goal-each__initiator-name">
      Created by:
      {{= initiator.name }}
      <a href="" class="goal-each__more-info">more info
        <i class="fa fa-caret-down"></i>
      </a>
    </div>
    <div class="goal-each__initiator-country">
      Country:
      {{= initiator.country }}
      <!-- Country:  goal.initiator.country.upcase if goal.initiator.present?  -->
    </div>
    <div class="goal-each__goal-description">
      {{= description }}
      <!--  goal.description if goal.description.present? -->
    </div>
    <div class="goal-each__created-date">
        <p class="goal-each__timestamp">Created: ({{= created_date_ago }} ago)</p>
    </div>

    <!--  Conditional: only if user if logged in -->
    <% if @current_user.present? %>
    <div class="goal-buddy-up__container">

      <a goal_id="{{= id }}" initiator="{{= initiator.name }}" goal="{{= title }}" href="/goals/{{= id}}/orders/new" class="btn btn__buddy-up--before">Buddy Up</a>
      <!-- link_to "BuddyUP", "/", {:goal_id => goal.id, :initiator => goal.initiator.name, :goal => goal.title.titleize, :class => 'btn btn__buddy-up--before' }  -->
    </div>
    <!--  end conditional -->

  </div>

  <% end %>
</script>

<!--  -->
<h1 class="main__title">All Goals</h1>

<div class="modal__container">
  <div class="modal">
    <h2 class="modal__title">Confirm</h2>
    <div class="modal__text">
      <p>Are you sure you want to
        <i class="modal-goal"></i>
        with
        <i class="modal-initiator"></i>?</p>
    </div>
    <div class="modal__buttons">
      <%= link_to "BuddyUP", "", {:class => 'btn btn__buddy-up--confirm', :method => 'POST' } %>
      <%= link_to "Cancel", "", :class => 'btn btn__buddy-up--cancel' %>
    </div>
  </div>

</div>
<!-- Adding Categories -->
<div class="goal-each__categories-title">
  <h2>Categories</h2>
</div>

<div id="categories-list">
  <%= render partial: 'categories_list', locals: { categories: @categories} %>
</div>

<div id="goals-filter"></div>
<!-- End Categories -->
<div class="btn-container">
  <!--  Conditional: only if user if logged in -->
  <% if @current_user.present? %>
  <%= link_to 'Create goal', new_goal_path, :class => 'btn' %>
  <!--  end conditional -->
<% else %>
  <p>Looks like you're not logged in!</p>
  <p>Why not
    <%= link_to "Sign up", signup_path, :class => 'goals-index__link' %>
    or
    <%= link_to "Login", login_path, :class => 'goals-index__link'%>?</p>
  <% end %>
</div>

<div id="all_goals"></div>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render :partial => 'form' %>

app/views/goals/show.html.erb
<h1 class="main__title">
  <%= @goal.title.titleize %>
</h1>

<% if @goal.acceptor.nil? %>
  <div class="goal-edit__container">
    <%= link_to "Edit", edit_goal_path , :class => 'goal-edit' %>
    <% if @goal.acceptor_id == nil %>
      <%= link_to 'Delete', goal_path(@goal), :method => :delete , :class => 'goal-delete' %>
    <% end %>
  </div>
<% end %>

<div class="goal-each__container">
  <div class="goal-each__initiator-name">
    Created by:
    <%= @goal.initiator.name if @goal.initiator.present? %>
  </div>
  <div class="goal-each__acceptor-name">
    Buddy:
    <%= @goal.acceptor.name if @goal.acceptor.present? %>
  </div>

  <div class="goal-show__goal-description">
    Description:
    <%= @goal.description %>
  </div>

  <div class="goal-show__goal-pledge">
    Pledged: <%= number_to_currency(@goal.amount) %>
  </div>

  <div class="goal-show__goal-status">
    Status: <%= goal_status(@goal) %>
  </div>


  <div class="goal-each__created-date">
    <% x = distance_of_time_in_words_to_now(@goal.created_at) %>
    <% y = time_tag(@goal.created_at) %>
    <p class="goal-each__timestamp">
      Created on:
      <%= y %>
      (<%= x %>
      ago)
    </p>
  </div>

  <% if !@goal.achieved %>
    <div class="btn-container">
      <button class="btn btn__goal-achieved">Goal Achieved</button>
    </div>
  <% end %>

</div>

<div id="subgoals__container" class="subgoals__container">
  <div class="subgoals__title">
    <h2>Subgoals</h2>
  </div>


  <div id="subgoal-form">

    <%= form_for ([@goal, @subgoal]), { remote: true } do |f| %>

      <fieldset>
        <%= f.label :title, :class => 'label' %>
        <%= f.text_field :title, :class => 'input subgoal-input' %>
      </fieldset>

      <div class="btn-container">
        <%= f.submit "Create Subgoal", :class => 'btn' %>
      </div>
    <% end %>

  </div>

  <div class="subgoals__toggle">
    <span class="subgoals__toggle-icon fa fa-arrow-up"></span>
  </div>

  <div id="subgoals-list">
    <%= render partial: 'subgoals_list', locals: { subgoals: @subgoals, goal: @goal } %>
  </div>

</div>

<div class="messages__container">
  <div id="backbone-container"></div>
</div>

<script id="appViewTemplate" type="text/template">
  <div class="goal-each__messages-title">
    <div class="messages__title">
      <h2>Messages</h2>
    </div>
  </div>
  <div id="magic-form"></div>
  <div class="messages__toggle">
    <i class="messages__toggle-icon fa fa-arrow-up"></i>
  </div>
  <div id="magic-messages"></div>
</script>

<script id="messageViewTemplate" type="text/template">
  <div class="magic-message__subject"></div>
</script>

<script id="messageFormViewTemplate" type="text/template">

  <fieldset>
    <label class="label">Subject:</label>
    <input type="text" class="input message-new-subject">
  </fieldset>

  <fieldset>
    <label class="label">Content:</label>
    <input type="text" class="input message-new-content">
  </fieldset>

  <div class="btn-container">
    <button class="btn">Create message</button>
  </div>

</script>