config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'lol' => 'pages#lol'

  resources :categories


  post '/goals/:goal_id/buddyup' => 'goals#buddyup'

  post '/goals/:goal_id/achieved' => 'goals#achieved'
  # post 'goals/:goal_id/buddyup' => 'goals#buddyup'

  resources :goals do
    resources :orders do
    end

    resources :messages do
    end

    resources :subgoals do
    end
  end

  get '/users/edit' => 'users#edit'

  resources :users, :only => [:new, :create, :index, :update, :show]

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Buddyup</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  </head>
  <body>

    <header class="header">
      <div class="header-logo__container">
        <a href="<%= root_path %>">
          <%= image_tag("logo-orange-1.png", :class => 'header-logo__image', :alt => 'BuddyUP') %>
        </a>
      </div>
    </header>
    <div class="menu-toggle__container">
      <i class="fa fa-caret-down"></i>
    </div>
      <nav class="nav__container">
        <ul class="nav-list">
          <li class="nav-list__item"><%= link_to 'GOALS', goals_path %></li>

          <!--  Conditional links -->
          <!--  User is logged in-->
          <% if @current_user.present? %>

          <!--  User is admin -->
          <% if @current_user.admin? %>

          <li class="nav-list__item"><%= link_to 'ALL USERS', users_path %></li>
          <li class="nav-list__item"><%= link_to 'CATEGORIES', categories_path %></li>
          <% end %>

          <!--  For non-admin users -->
          <li class="nav-list__item"><%= link_to "VIEW PROFILE", user_path(@current_user) %></li>

          <li class="nav-list__item">
            <%= link_to "EDIT PROFILE", users_edit_path %></li>

          <li class="nav-list__item"><%= link_to "LOGOUT #{@current_user.email}", login_path, :method => :delete %></li>

          <!--  User is not logged in -->
        <% else %>
          <li class="nav-list__item"><%= link_to "SIGN UP", signup_path %></li>
          <li class="nav-list__item"><%= link_to "LOGIN", login_path %></li>
          <% end %>
          <!--  End conditional links -->

        </ul>
      </nav>

    <% if flash[:error].present? %>
    <h2 class="error">
      <%= flash[:error] %>
    </h2>
    <% end %>

    <div class="main__container">
      <%= yield %>
    </div>

    <footer class="footer">
      &copy; 2016 BuddyUP
    </footer>

  </body>

</html>